services:
  stats-server:
    build: ./statistic/server
    image: statistic-server
    container_name: statistic-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5431/statistic
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    expose:
      - "5431"
    ports:
      - "5431:5431"
    #    volumes:
    #      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statistic
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - PGPORT=5431
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-service:
    build: ./statistic/client
    image: statistic-client
    container_name: statistic-client
    ports:
      - "8081:8081"
    depends_on:
      - stats-server
    environment:
      - STATISTIC_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    container_name: postgres-explore-db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    #    volumes:
    #      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explore
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./explore
    image: explore
    container_name: explore
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATISTIC_SERVICE_URL=http://stats-service:8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
